ports:
  - port: 8080
    onOpen: open-browser

tasks:
  - name: docker-daemon
    before: sudo docker-up
    
  - name: keycloak
    before:
      echo 'Waiting for docker daemon to start' &&
      while [ ! -S /var/run/docker.sock ]; do sleep 1; done;
    init: >-
      export IMAGE="${IMAGE:=quay.io/keycloak/keycloak:12.0.4}" &&
      export KEYCLOAK_USER="${KEYCLOAK_USER:=admin}" &&
      export KEYCLOAK_PASSWORD="${KEYCLOAK_PASSWORD:=password}" &&
      export KEYCLOAK_STATISTICS="${KEYCLOAK_STATISTICS:=all}" &&
      export KEYCLOAK_LOGLEVEL="${KEYCLOAK_LOGLEVEL:=INFO}" &&
      export JAVA_OPTS_APPEND="${JAVA_OPTS_APPEND:=-Dkeycloak.profile.feature.upload_script=enabled -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.account2=enabled -Dkeycloak.profile.feature.account_api=enabled}" &&
      docker-compose up -d &&
      docker logs -f keycloak