version: '3.8'
services:
  keycloak:
      container_name: keycloak
      image: ${IMAGE}
      command: start-dev
      environment:
        KC_DB: dev-mem
        KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
        KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
        KC_METRICS_ENABLED: "true"
        KC_HEALTH_ENABLED: "true"
        KC_PROXY_HEADERS: xforwarded
        KC_LOG_CONSOLE_LEVEL: ${KC_LOG_CONSOLE_LEVEL}
        JAVA_OPTS_APPEND: "${JAVA_OPTS_APPEND}"
      ports:
        - 8080:8080